name: suggest_a_feature
description: Ready-made Flutter package for collecting suggestions from users.
version: 0.4.1
repository: https://github.com/What-the-Flutter/Suggest-a-Feature
homepage: https://pub.dev/packages/suggest_a_feature

topics:
  - suggestions
  - bug-reporting
  - feedback

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  intl: ^0.18.1
  wtf_sliding_sheet: ^1.1.3

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  assets:
    - assets/
